### PR TITLE
Update files array in all-contributorsrc

### PR DESCRIPTION
**Pull request by zhang1pr**
For #25, I tested [this](https://github.com/zhang1pr/explore-react-guide/pull/2/commits) on my branch. The bot can update 2 files now.

I updated the array of files to be affected. The other changes were generated by cli. So it's better to keep them maybe.

Note that #contributors- is an id for anchor so it has to have - at the end.

### CODE REVIEW

**Review by M0nica — COMMENTED** [review]
Thanks, I think this will work. Can you update your PR to address the merge conflicts?

**Comment by zhang1pr** [comment]
Accidentally closed this pull request when I updated my fork. Reopen now.

**Comment by zhang1pr** [comment]
@M0nica Sure, it's done.

**Comment by M0nica** [comment]
Thanks @zhang1pr!

**Pull request merged**
